/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/driverprofile` | `/driverprofile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/driverprofile` | `/driverprofile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(rider)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(rider)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(rider)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/driverprofile${`?${string}` | `#${string}` | ''}` | `/driverprofile${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(rider)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(rider)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(rider)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/driverprofile` | `/driverprofile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(rider)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
